name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull
      uses: actions/checkout@v2
    - name: Install .Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/sensemaking/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Nuget Restore
      run: dotnet restore
    - name: Build Solution
      run: dotnet build --configuration Release --no-restore
    - name: Package
      run: dotnet pack
    - name: Add Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/sensemaking/index.json -n GitHub -u sensemaking -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text    
    - name: Push Package 
      run: dotnet nuget push $GITHUB_WORKSPACE\Core.nupkg -source GitHub